### ISSUE TITLE
No module named 'tweepy'

### ISSUE THREAD

**Issue by VictorLzm** [After-Hours-Bot/AfterHours-API#1]
Hi!
I wanted to try your bot today and setup everything needed in bot.py . 
but by hiting the start line bash propted me:
```
root@xxx:/opt/afterhours-bot# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    import tweepy, time, os
ModuleNotFoundError: No module named 'tweepy'
```

all i did before:
`   git clone https://github.com/0V0-BOT-DEVELOPER/afterhours-bot`
`   git clone https://github.com/thisisppn/reddit-media-downloader`
`   cp reddit-media-downloader/reddit.py afterhours-bot/
``   cd afterhours-bot/
``   python3 bot.py
`   -> Failed
`   pip install tweepy requests
``   python3 bot.py
`   ->Failed

**Comment by 808-Dev** [comment]
This may be a version thing. Try to use 'pip3 install tweepy'. Python is kinda picky when it comes to versions and installing libraries. Sorry about the late response.

**Comment by VictorLzm** [comment]
Yay solved! Shame i didn't think about it earlier
