### ISSUE TITLE
Read-only application cannot POST.

### ISSUE THREAD

**Issue by VictorLzm** [After-Hours-Bot/AfterHours-API#2]
Hi, 
by running the `python3 bot.py` command, it gets an error:

```
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    api.send_direct_message(admin_id,'I am now online!')
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 458, in send_direct_message
    return self._send_direct_message(json_payload=json_payload)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/usr/local/lib/python3.7/dist-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Read-only application cannot POST.

```

But i double chacked my [Project Page](https://developer.twitter.com/en/portal/projects/) and it shows that i'm in rws : 
![image](https://user-images.githubusercontent.com/6512397/102204186-d3eff880-3ec9-11eb-80ea-0491b6ef8780.png)

**Comment by 808-Dev** [comment]
That's pretty odd. Try to reset your credentials, and insert them again. Also, try to get your user id again. I will look into this, and update if I can find the problem.

**Comment by 808-Dev** [comment]
From what I have tried, I was unable to see any issues with the code working. If you could send me your code, I can take a look at it for you to see what's up with it.
